### ISSUE TITLE
大神好，咨询下

### ISSUE THREAD

**Issue by weeknote** [WangYihang/Webshell-Sniper#3]
最近在打ctf比赛，也想自己搞一个集成化的管理工具维护自己的gamebox，看到您的Webshell-Sniper感觉写得很好~膜拜。
就是想问一下您，按照现有的方式，我给自己的站留个eval后门的话别人不也能利用了嘛，但我试了一下在后门外面套一层REMOTE_ADDR限制访问IP好像Sniper就上不去了。
请问大神有木有好的建议和解决方式呢？或者您还有什么awd的自动化脚本和经验、文章可以借鉴的，求推荐。
再次感谢

**Comment by WangYihang** [comment]
你自己留后门的话完全可以在后门那里做身份验证呀，比如
```
if("117914340cdc01f0aa486b5b077374ef" = $_COOKIE['password']){
    // do some thing
} else {
    // f**k off hacker!
}
```
这样只要别人拿不到你利用的流量中发送的 `$_COOKIE['password']` 就可以了
但是这种方式事实上是把安全性放在了对参数（密码）的保密上，如果别人知道密码的话也可以连接
还可以考虑一下写一个利用比较复杂的 WebShell（或者使用某种方式对代码进行混淆），一般情况下比赛时间不会很长，别的队伍也不会有时间对你的后门进行分析。并且连接方式可以根据某种算法进行随机，这样可以在一定程度上对抗流量重放攻击。

**Comment by WangYihang** [comment]
你要自己加认证的话，需要自己定义这个函数，对外暴露一个执行任意 PHP 代码的接口即可：
> https://github.com/WangYihang/Webshell-Sniper/blob/master/core/webshell/WebShell.py#L41-L59

![image](https://user-images.githubusercontent.com/16917636/45486095-791c4380-b78c-11e8-8f68-fc853d1539c3.png)

其实 WebShell 的连接是非常灵活的，例如菜刀这种只是实现了很简单的连接方式。这个工具最开始在设计的时候也是不太像这么死板，但是考虑到易用性就只支持了几种方式，如果需要定制的话，只需要重写这个函数即可
